# Generated by Django 4.1.6 on 2023-02-08 10:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Prénom', max_length=25)),
                ('last_name', models.CharField(help_text='Nom', max_length=25)),
                ('email', models.EmailField(help_text='Email client', max_length=100)),
                ('phone', models.CharField(blank=True, help_text='Télephone client fixe', max_length=20)),
                ('mobile', models.CharField(help_text='Téléphone client mobile', max_length=20)),
                ('company_name', models.CharField(blank=True, help_text='Société clinet si professionnel', max_length=250)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, help_text='Date de création client')),
                ('datetime_updated', models.DateTimeField(auto_now=True, help_text='Date de modification client')),
                ('sales_contact', models.ForeignKey(blank=True, help_text="Contact vendeur assigné par l'équipe de support", null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clients',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, help_text='Date création évènement')),
                ('datetime_updated', models.DateTimeField(auto_now=True, help_text='Date de modification événement')),
                ('attendees', models.IntegerField(blank=True, help_text="Nombre d'invités", null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('event_date', models.DateField(blank=True, help_text="Date de l'évènement Format: AAAA-MM-JJ", null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes')),
                ('status', models.BooleanField(default=False, help_text='Terminé O/N')),
                ('client', models.ForeignKey(help_text='contact client', on_delete=django.db.models.deletion.CASCADE, to='crm.client')),
                ('support_contact', models.ForeignKey(blank=True, help_text='Contact support', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Evènements',
                'ordering': ['status', 'event_date'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, help_text='Date de création du contrat')),
                ('datetime_updated', models.DateTimeField(auto_now=True, help_text='Date de modification du contrat')),
                ('status_sign', models.BooleanField(default=False, help_text='contrat signé O/N')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant du contrat', max_digits=9)),
                ('payment_due', models.DateField(help_text='Date de paiement Format: AAAA-MM-JJ')),
                ('client', models.ForeignKey(help_text='Client signataire', on_delete=django.db.models.deletion.CASCADE, to='crm.client')),
                ('sales_contact', models.ForeignKey(help_text="Contact vendeur attribué par l'équipe support", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contrats',
                'ordering': ['client', '-datetime_created'],
            },
        ),
    ]
