# Generated by Django 4.1.6 on 2023-02-20 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0003_alter_client_sales_contact'),
    ]

    operations = [

        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(help_text='Client signataire', on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='crm.client'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sales_contact',
            field=models.ForeignKey(blank=True, help_text="Contact vendeur attribué par l'équipe management", limit_choices_to={'team_id': 2}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='support_contact',
            field=models.ForeignKey(blank=True, help_text='Contact support', limit_choices_to={'team_id': 3}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
