# Generated by Django 4.1.6 on 2023-02-21 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_remove_event_client_event_contract_event_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contract',
            field=models.OneToOneField(limit_choices_to={'status_sign': True}, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='crm.contract'),
        ),
    ]
